name: Update badges

on:
  schedule:
    # Runs at 11:31 UTC
    - cron: "53 11 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges Readme
        uses: pemtajo/badge-readme@2.3.0
        with: 
          CREDLY_USER: aaron-will-djaba 
          # optional, but default will use the same from github
